name: PR Preview Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: write

concurrency:
  group: "pages-${{ github.event.pull_request.number }}"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run checks
        run: npm run check

      - name: Build application
        run: npm run build
        env:
          # Set base path for the PR preview
          NEXT_PUBLIC_BASE_PATH: /zure-vibecoding/pr-${{ github.event.pull_request.number }}

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Create preview directory structure
        run: |
          mkdir -p ./preview-site/pr-${{ github.event.pull_request.number }}
          cp -r ./out/* ./preview-site/pr-${{ github.event.pull_request.number }}/

          # Create or update index.html for preview listing
          cat > ./preview-site/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
              <title>PR Previews - Business Stalker</title>
              <style>
                  body { font-family: system-ui, sans-serif; margin: 40px; }
                  .preview-link { display: block; padding: 12px; margin: 8px 0; 
                                 background: #f5f5f5; border-radius: 6px; text-decoration: none; }
                  .preview-link:hover { background: #e5e5e5; }
              </style>
          </head>
          <body>
              <h1>Business Stalker - PR Previews</h1>
              <p>Available preview deployments:</p>
              <a href="./pr-${{ github.event.pull_request.number }}/" class="preview-link">
                  PR #${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}
              </a>
          </body>
          </html>
          EOF

      - name: Upload to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./preview-site"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const previewUrl = `https://${{ github.repository_owner }}.github.io/zure-vibecoding/pr-${prNumber}/`;

            // Check if we already commented
            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber
            });

            const botComment = comments.data.find(comment => 
              comment.user.type === 'Bot' && 
              comment.body.includes('🚀 PR Preview deployed')
            );

            const commentBody = `🚀 **PR Preview deployed!**

            You can preview this PR at: ${previewUrl}

            📱 **Visual verification available** - Test your changes before merging!

            ---
            ✅ Build completed successfully
            🔗 Preview will be updated automatically on new commits
            🧹 Preview will be cleaned up when PR is closed/merged`;

            if (botComment) {
              // Update existing comment
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: commentBody
              });
            } else {
              // Create new comment
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: commentBody
              });
            }
